export const OrdersData = [
	{
		id: 142235,
		recipient: "Nikhil Thorat",
		totalProducts: 2,
		dileveryAddress: "Balaji Nagar, Daund - 413801, Pune Maharashtra",
		amount: 3299,
		status: "processing",
	},
	{
		id: 142235,
		recipient: "Nikhil Thorat",
		totalProducts: 2,
		dileveryAddress: "Balaji Nagar, Daund - 413801, Pune Maharashtra",
		amount: 3299,
		status: "processing",
	},
	{
		id: 142235,
		recipient: "Nikhil Thorat",
		totalProducts: 2,
		dileveryAddress: "Balaji Nagar, Daund - 413801, Pune Maharashtra",
		amount: 3299,
		status: "processing",
	},
	{
		id: 142235,
		recipient: "Nikhil Thorat",
		totalProducts: 2,
		dileveryAddress: "Balaji Nagar, Daund - 413801, Pune Maharashtra",
		amount: 3299,
		status: "processing",
	},
	{
		id: 142235,
		recipient: "Nikhil Thorat",
		totalProducts: 2,
		dileveryAddress: "Balaji Nagar, Daund - 413801, Pune Maharashtra",
		amount: 3299,
		status: "processing",
	},
	{
		id: 142235,
		recipient: "Nikhil Thorat",
		totalProducts: 2,
		dileveryAddress: "Balaji Nagar, Daund - 413801, Pune Maharashtra",
		amount: 3299,
		status: "processing",
	},
	{
		id: 142235,
		recipient: "Nikhil Thorat",
		totalProducts: 2,
		dileveryAddress: "Balaji Nagar, Daund - 413801, Pune Maharashtra",
		amount: 3299,
		status: "processing",
	},
	{
		id: 142235,
		recipient: "Nikhil Thorat",
		totalProducts: 2,
		dileveryAddress: "Balaji Nagar, Daund - 413801, Pune Maharashtra",
		amount: 3299,
		status: "processing",
	},
];
